name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [gcc-debug, gcc-asan, gcc-ubsan, gcc-tsan, clang-debug, clang-asan, clang-ubsan, clang-tsan]

    steps:
    - name: Install gcc-11
      run: |
        sudo apt update
        sudo apt install gcc-11 g++-11
        
    - name: Install clang-12
      run: |
        sudo apt update
        sudo apt install clang-12
        
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.22.x'
        
    - name: Install ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
    
    - name: Install gtest
      run: sudo apt-get install libgtest-dev
      
    - name: Cmake
      run: |
        cd ${{runner.workspace}}/CmakeUtilities
        cmake . --preset=${{matrix.preset}} -DBUILD_EXAMPLES=ON
      
    - name: Build
      run: |
        cd ${{runner.workspace}}/CmakeUtilities/cmake-build-${{matrix.preset}}
        ninja
      
    - name: Test
      run: |
        cd ${{runner.workspace}}/CmakeUtilities/cmake-build-${{matrix.preset}}
        ninja build-and-test
